# Basic configuration for the Symfony framework features
framework:
    translator:
        enabled: true
        fallback: ["%locale%"]
        paths: ['%kernel.project_dir%/translations']

    default_locale:  "%locale%"
    secret:          Psssst
